version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./public:/app/public
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app/app/frontend
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped 